# Generated by Django 6.0.7 on 2026-07-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('wh_admin_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addstock',
            name='wh_id',
            field=models.ForeignKey(db_column='wh_id', on_delete=django.db.models.deletion.CASCADE, related_name='add_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addstock',
            name='wh_logs',
            field=models.ForeignKey(db_column='wh_logs', on_delete=django.db.models.deletion.CASCADE, to='wh_admin_logs.warehouseadminlogs'),
        ),
        migrations.AlterUniqueTogether(
            name='addstock',
            unique_together={('wh_id', 'wh_logs')},
        ),
    ]
