# Generated by Django 6.0.7 on 2026-07-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAdminLogs',
            fields=[
                ('wh_logs', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wh_proof', models.CharField(max_length=200)),
                ('wh_id', models.ForeignKey(db_column='wh_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wh_admin_logs',
            },
        ),
    ]
