# Generated by Django 6.0.7 on 2026-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('mrf_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NOT APPROVED', 'Not Approved')], default='PENDING', max_length=20)),
                ('release_status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released'), ('NOT RELEASED', 'Not Released')], default='PENDING', max_length=20)),
                ('mrf_files', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'material_request',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('sub_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'release',
            },
        ),
    ]
