# Generated by Django 6.0.7 on 2026-07-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_requests', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='requestor_email',
            field=models.ForeignKey(db_column='requestor_email', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='release',
            name='mrf_id',
            field=models.ForeignKey(db_column='mrf_id', on_delete=django.db.models.deletion.CASCADE, to='material_requests.materialrequest'),
        ),
        migrations.AddField(
            model_name='release',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
